# Generated by Django 5.1.1 on 2024-12-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=50)),
                ("cpf", models.CharField(max_length=11)),
                ("tel", models.CharField(max_length=12)),
                ("website", models.CharField(blank=True, max_length=30)),
                ("city", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "crm_customer",
            },
        ),
    ]
