# Generated by Django 5.1.1 on 2024-09-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("enterprise", models.CharField(max_length=30)),
                ("cpf", models.CharField(max_length=11)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.IntegerField(max_length=30)),
                ("tel", models.CharField(max_length=30)),
                ("website", models.CharField(max_length=30)),
                (
                    "positon_enterprise",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("andress", models.CharField(max_length=40)),
                ("cep", models.CharField(max_length=40)),
                ("city", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=30)),
                ("admin", models.BooleanField()),
            ],
        ),
    ]
