# Generated by Django 5.1.1 on 2024-09-17 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "auth_users",
            },
        ),
        migrations.CreateModel(
            name="UserClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enterprise", models.CharField(max_length=30)),
                ("cpf", models.CharField(max_length=11)),
                ("tel", models.CharField(max_length=30)),
                ("website", models.CharField(max_length=30)),
                (
                    "positon_enterprise",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("andress", models.CharField(max_length=40)),
                ("cep", models.CharField(max_length=40)),
                ("city", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "client_data",
            },
        ),
        migrations.CreateModel(
            name="UserAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel", models.CharField(max_length=30)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="authUser.user"
                    ),
                ),
            ],
            options={
                "db_table": "admin_data",
            },
        ),
    ]
