# Generated by Django 5.1.1 on 2024-10-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authUser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("client", "Client")],
                default="client",
                max_length=6,
            ),
        ),
    ]
