# Generated by Django 5.1.1 on 2024-09-17 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authUser", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="crm_users",
        ),
        migrations.AlterModelTable(
            name="useradmin",
            table="crm_admin_data",
        ),
        migrations.AlterModelTable(
            name="userclient",
            table="crm_client_data",
        ),
    ]
