# Generated by Django 5.1.1 on 2024-10-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authUser", "0002_user_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useradmin",
            old_name="nivel",
            new_name="business",
        ),
    ]
